version: 0.0
os: windows
files:
  - source: /petclinic.war
    destination: C:\Users\Administrator\Apache9\webapps
hooks:
  AfterInstall:
    - location: C:\Users\Administrator\Apache9\bin\startup.bat
      timeout: 900